# Osquery sample deployment template

---

releases:
- name: osquery
  url: git+https://github.com/Uptycs/osquery-boshrelease
  version: 5.0.2.9-Uptycs-202111112102 # Change to the latest Osquery version

addons:
- name: osquery
  jobs:
  - name: osquery
    release: osquery
    properties:
      uptycs:
        hostname: CHANGE-ME # Change to your Uptycs tenant hostname. Example: tenant.uptycs.io
        secret: CHANGE-ME   # Download the secret from Uptycs SaaS platform